apiVersion: k8s.cloudogu.com/v1
kind: Dogu
metadata:
  name: nginx-ingress
  annotations:
    test: dev
  labels:
    dogu: nginx-ingress
    app: nginx-ingress
spec:
  name: k8s/nginx-ingress
  version: 1.3.0-1