apiVersion: k8s.cloudogu.com/v1
kind: Dogu
metadata:
  name: nginx-static
  annotations:
    test: dev
  labels:
    dogu.name: nginx-static
    app: nginx-static
spec:
  name: k8s/nginx-static
  version: 1.23.1-2